

export const ADD_COMMAND = "ADD_COMMAND";
export const ADD_COMMAND_SUCCESS = "ADD_COMMAND_SUCCESS";
export const ADD_COMMAND_FAIL = "ADD_COMMAND_FAIL";


export const GET_COMMAND = "GET_COMMAND";
export const GET_COMMAND_SUCCESS = "GET_COMMAND_SUCCESS";
export const GET_COMMAND_FAIL = "GET_COMMAND_FAIL";