

export const ADD_PIECES = "ADD_PIECES";
export const ADD_PIECES_SUCCESS = "ADD_PIECES_SUCCESS";
export const ADD_PIECES_FAIL = "ADD_PIECES_FAIL";


export const GET_PIECES = "GET_PIECES";
export const GET_PIECES_SUCCESS = "GET_PIECES_SUCCESS";
export const GET_PIECES_FAIL = "GET_PIECES_FAIL";

export const EDIT_PIECES ="EDIT_PIECES";
export const EDIT_PIECES_SUCCESS ="EDIT_PIECES_SUCCESS";
export const EDIT_PIECES_FAIL ="EDIT_PIECES_FAIL";

export const DELETE_PIECES = "DELETE_PIECES";
export const DELETE_PIECES_SUCCESS = "DELETE_PIECES_SUCCESS";
export const DELETE_PIECES_FAIL = "DELETE_PIECES_FAIL";


// export const GET_PIECES_BY_CATHEGORY = "GET_PIECES_BY_CATHEGORY";
// export const GET_PIECES_BY_CATHEGORY_SECCESS = "GET_PIECES_BY_CATHEGORY";
// export const GET_PIECES_BY_CATHEGORY_FAIL = "GET_PIECES_BY_CATHEGORY";



